export const FETCH_BEERS_FULFILLED = 'FETCH_BEERS_FULFILLED';
export const FETCH_BEERS_REJECTED = 'FETCH_BEERS_REJECTED';
export const FETCH_BEERS = 'FETCH_BEERS';
export const SORT_BEERS = 'SORT_BEERS';
export const FILTER_BEERS = 'FILTER_BEERS';
export const SHOW_BEER_DETAILS = 'SHOW_BEER_DETAILS';
export const HIDE_BEER_DETAILS = 'HIDE_BEER_DETAILS';
